#!/bin/sh

alias l="/bin/ls --group-directories-first --color=auto"
alias ls="/bin/ls --group-directories-first --color=auto"
alias ll="/bin/ls -lh --group-directories-first --color=auto"
alias la="/bin/ls -A --group-directories-first --color=auto"
alias lla="/bin/ls -lAh --group-directories-first --color=auto"
alias cd="cdls"
alias df='/usr/bin/df -h'
alias free='free -m'
alias np="$EDITOR PKGBUILD"
alias kh='cut -d "," -f 1 ~/.ssh/known_hosts | cut -d " " -f 1 | uniq'
alias zshrc="$EDITOR $HOME/.zshrc"
alias zshenv="$EDITOR $HOME/.zshenv"
alias src="exec $SHELL"
alias vimrc="$EDITOR $HOME/.config/nvim/init.lua"
alias vrc="cd $HOME/.config/nvim/ && $EDITOR"
alias vim=$EDITOR
alias open="xdg-open"
alias locate="locate -e"
alias gdb="gdb -tui"
alias y="sudo dnf upgrade --refresh && sudo flatpak update && pip3 install -U pyright && nvim +PackerSync"
alias ytdl="youtube-dl"
alias dot="/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME"
alias hd="hexdump -C"
alias maxima="rmaxima"
alias tmux="tmux -u"
alias diff="diff --color=auto"
alias governor="cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor"
alias grub-update="sudo grub2-mkconfig -o /boot/grub2/grub.cfg"
alias visudo="sudo EDITOR=$EDITOR visudo"
