#!/bin/zsh

alias l="/bin/ls --group-directories-first --color=auto"
alias ls="/bin/ls --group-directories-first --color=auto"
alias ll="/bin/ls -lh --group-directories-first --color=auto"
alias la="/bin/ls -A --group-directories-first --color=auto"
alias lla="/bin/ls -lAh --group-directories-first --color=auto"
alias cd="cdls"
alias df='/usr/bin/df -h'
alias free='free -m'
alias np="$EDITOR PKGBUILD"
alias kh='cut -d "," -f 1 ~/.ssh/known_hosts | cut -d " " -f 1'
alias zshrc="$EDITOR $HOME/.zshrc"
alias zshenv="$EDITOR $HOME/.zshenv"
alias src="exec $SHELL"
alias vimrc="$EDITOR $HOME/.config/nvim/init.lua"
alias vim=$EDITOR
alias open="xdg-open"
alias locate="locate -e"
alias gdb="gdb -tui"
alias y="yay"
alias ytdl="youtube-dl"
alias dot="/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME"
alias hd="hexdump -C"
alias maxima="rmaxima"
alias ftp="ncftp"
alias tmux="tmux -u"
alias diff="diff --color=auto"
alias nnn="/usr/bin/nnn -P p -T v"
