#!/bin/bash

function cht() {
    defaultcolor=${2:-xcode}
    curl -s "cheat.sh/$1?style=$defaultcolor"
}

function fixpk() {
    sudo pkcon -v -p repair
    sudo pkcon refresh force -c -1 -v -p
}

function zsh_directory_name() {
    emulate -L zsh
    [[ $1 == d ]] || return
    while [[ $2 != / ]]; do
        if [[ -e $2/.git ]]; then
            typeset -ga reply=(${2:t} $#2)
            return
        fi
        2=${2:h}
    done
    return 1
}

function rainbowband() {
    awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
    for (colnum = 0; colnum<77; colnum++) {
        r = 255-(colnum*255/76);
        g = (colnum*510/76);
        b = (colnum*255/76);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
    }'
}

function mkcd() {
    /usr/bin/mkdir -p $1 && cd $1
}

function cpcd() {
    /usr/bin/mkdir -p $2 && cp $1 $2 && cd $2
}

function mvcd() {
    /usr/bin/mv $1 $2 && cd $2
}

function cdls() {
    builtin cd "$@" > /dev/null 2>&1 || /usr/bin/echo "no such directory '$@'"
    lscwd
}

function lscwd() {
    tot=$(/bin/ls -1 -f | wc -l)
    visible=$(/bin/ls -1 -U --color=never | wc -l)
    if [[ $tot -eq 2 ]]; then
        /bin/echo "This directory is empty"
    elif [[ $visible -eq 0 ]]; then
        ls -A
    else
        ls
    fi
}

function pcs() {
    for i in {0..7}; do
        echo -en "\e[${1}$((30+$i))m \u2588\u2588 \e[0m";
    done;
}

function blox() {
    printf "\n%s\n%s\n\n" "$(pcs)" "$(pcs '1;')"
}

# ex - archive extractor
# usage: ex <file>
function ex() {
    local c e i

    (($#)) || return

    for i; do
        c=''
        e=1

        if [[ ! -r $i ]]; then
            echo "$0: file is unreadable: \`$i'" >&2
            continue
        fi

        case $i in
            *.t@(gz|lz|xz|b@(2|z?(2))|a@(z|r?(.@(Z|bz?(2)|gz|lzma|xz)))))
                   c=(bsdtar xvf);;
            *.7z)  c=(7z x);;
            *.Z)   c=(uncompress);;
            *.bz2) c=(bunzip2);;
            *.exe) c=(cabextract);;
            *.gz)  c=(gunzip);;
            *.rar) c=(unrar x);;
            *.xz)  c=(unxz);;
            *.zip) c=(unzip);;
            *.zst) c=(unzstd);;
            *)     echo "$0: unrecognized file extension: \`$i'" >&2
                   continue;;
        esac

        command "${c[@]}" "$i"
        ((e = e || $?))
    done
    return "$e"
}
