#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap           12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config pointer_modifier     mod1

# color definitions
normal="#dbc7f6"
focused="#56ba99"
background="#c0e8f7"

# split style
bspc config automatic_scheme alternate

# border colors
bspc config active_border_color "$normal"
bspc config normal_border_color "$normal"
bspc config focused_border_color "$focused"

# mouse cursor configuration
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false

# window rules
bspc rule -a 'Zathura' state=tiled split_ratio=0.55
bspc rule -a 'Gimp-2.10' state=fullscreen follow=on
bspc rule -a 'Gimp' state=fullscreen follow=on
bspc rule -a 'zoom' state=floating desktop='^2' follow=on center=true
bspc rule -a 'Kanaconvert' state=floating follow=on center=true
bspc rule -a 'retroarch' state=fullscreen
bspc rule -a 'Pavucontrol' state=floating center=true

# polybar
$HOME/.config/polybar/launch.sh &

# background programs
killall udiskie
killall nm-applet
killall checkfullscreen.sh
killall feh

# restarts background programs
udiskie -t &
nm-applet &
pkill dunst &

# swaps escape and caps lock
setxkbmap -option ''
setxkbmap -option caps:swapescape

# run script to disable locking if application in full screen
$HOME/.config/i3/checkfullscreen.sh &

# set background
feh --bg-scale ~/Pictures/background.png || hsetroot -solid "$background" &

# screensaver default 10 mins timeout
xset s 600 600 

# keyboard and mouse settings
xset r rate 200 25
xinput --set-prop 'pointer:Razer Razer Viper' 'libinput Accel Speed' -0.75

# use i3lock to lock the screen 
xss-lock -v --transfer-sleep-lock ~/.config/i3/lock.sh
# DO NOT PUT ANYTHING ELSE BELOW THIS LINE! It will not get executed
