#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config pointer_modifier     mod1

# color definitions
normal="#d8d8d8"
focused="#ff79c6"
background1="#d4cef3"
background2="#c0e8f7"

# split style
bspc config automatic_scheme alternate

# border colors
bspc config active_border_color "$normal"
bspc config normal_border_color "$normal"
bspc config focused_border_color "$focused"

# mouse cursor configuration
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

# window rules
bspc rule -a 'Zathura' state=tiled
bspc rule -a 'discord' desktop='^4' follow=off

# standard floated applications
floatapps=(
	'Gimp'
	'Kanaconvert'
	'Pavucontrol'
	'Inkscape'
	'matplotlib'
)

for appname in "${floatapps[@]}";do
	bspc rule -a "$appname" state=floating
done

# float applications to put on desktop 5
# (recommended for multi window applications)
floatappsMove=(
	'Gimp-2.10'
	'zoom'
	'retroarch'
	'Anki'
	'x2goclient'
)

# set window 5 to only floating windows
pkill -f floating.sh
$HOME/.config/bspwm/floating.sh &

for appname in "${floatappsMove[@]}";do
	bspc rule -a "$appname" state=floating follow=on center=true desktop='^5'
done

# run script to disable locking if application in full screen
pkill -f checkfullscreen.sh
checkfullscreen.sh &

# run script for desktop renaming
pkill -f desktoprename.sh
~/.config/bspwm/desktoprename.sh &

# background programs
pkill -f clipmenud
pkill -f udiskie
pkill -f nm-applet
pkill -f blueman-applet
pkill dunst &

# restarts background programs
udiskie -t &
blueman-applet &
nm-applet &
clipmenud &

# polybar
$HOME/.config/polybar/launch.sh &

# swaps escape and caps lock
setxkbmap -option caps:swapescape

# set background
$HOME/.fehbg > /dev/null 2>&1 || hsetroot -add "$background1" -add "$background2" -gradient 30 &

# screensaver default 10 mins timeout
xset s 600 600 

# keyboard and mouse settings
xset r rate 200 25
xinput --set-prop 'pointer:Razer Razer Viper' 'libinput Accel Speed' -0.75

# use i3lock to lock the screen 
xss-lock -v --transfer-sleep-lock lock.sh

# DO NOT PUT ANYTHING ELSE BELOW THIS LINE! It will not get executed
