#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap           10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config pointer_modifier     mod1

# color definitions
normal="#dbc7f6"
focused="#56c6ca"
background="#edead9"

# border colors
bspc config active_border_color "$normal"
bspc config normal_border_color "$normal"
bspc config focused_border_color "$focused"

# mouse cursor configuration
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false

# window rules
bspc rule -a 'Zathura' state=tiled
bspc rule -a 'discord' state=pseudo_tiled follow=on
bspc rule -a 'minecraft-launcher' state=fullscreen
bspc rule -a 'Gimp-2.10' state=fullscreen follow=on
bspc rule -a 'Gimp' state=fullscreen follow=on
bspc rule -a 'zoom' state=floating desktop='^2' follow=on center=true
bspc rule -a 'Kanaconvert' state=floating follow=on center=true
bspc rule -a 'Anki' state=pseudo_tiled follow=on center=true
bspc rule -a 'retroarch' state=fullscreen
bspc rule -a 'Pavucontrol' state=pseudo_tiled follow=on center=true

# polybar
$HOME/.config/polybar/launch.sh &

# background programs
killall udiskie
killall nm-applet
killall checkfullscreen.sh
killall feh
killall xwinwrap

udiskie -t &
nm-applet &
pkill dunst &

# set background
feh --bg-scale ~/Pictures/background.png || hsetroot -solid "$background" &

# set live background
# xwinwrap -ov -g 1920x1080+0+0 -- mpv -wid WID "$HOME/PATH/TO/VIDEO" \
#    --no-osc \
#    --no-osd-bar \
#    --loop-file \
#    --player-operation-mode=cplayer \
#    --no-audio \
#    --panscan=1.0 \
#    --no-input-default-bindings &

# screensaver default 10 mins timeout
xset s 600 600 

# keyboard and mouse settings
xset r rate 200 25
xinput --set-prop 'pointer:Razer Razer Viper' 'libinput Accel Speed' -0.75

# use i3lock to lock the screen
xss-lock -v --transfer-sleep-lock ~/.config/i3/lock.sh

# run script to disable locking if application in full screen
$HOME/.config/i3/checkfullscreen.sh &
